package com.commerce.platform.contracts.model;

public enum FailureReason {
    PAYMENT_AUTHORIZATION_DECLINED,

    COLD_ITEM_OUT_OF_STOCK,
    COLD_CHAIN_CAPACITY_EXCEEDED,
    STOCK_RESERVATION_EXPIRED,

    DELIVERY_SLOT_UNAVAILABLE,
    DELIVERY_ZONE_NOT_SUPPORTED,
    PICKER_ASSIGNMENT_FAILED,

    ORDER_ALREADY_CANCELLED,
    COMPENSATION_FAILED,
    UNKNOWN
}
