package com.commerce.platform.contracts.model;

public enum SagaStep {
    GROCERY_ORDER_CREATED,

    PAYMENT_AUTHORIZED,
    PAYMENT_AUTHORIZATION_RELEASED,

    COLD_STOCK_RESERVED,
    COLD_STOCK_RESERVATION_RELEASED,

    DELIVERY_SLOT_ALLOCATED,
    DELIVERY_SLOT_RELEASED,

    PICKER_ASSIGNED,

    GROCERY_ORDER_CONFIRMED,
    GROCERY_ORDER_CANCELLED
}
